# =============================================================================
# capitulo2_pseudobulk_de.R — Pseudobulk Differential Expression & GO (Part 2)
# =============================================================================
# Requires: pbmc_harmony_curated.rds generated by capitulo1_single_cell.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "/workspace/workflow_nuevo"
DATA_DIR     <- "/workspace/."
base_dir     <- file.path(DATA_DIR, "resultados")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

set.seed(1807)


# =============================================================================
# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# LOAD — CURATED OBJECT FROM PART 1
# =============================================================================
# Loads the final annotated object produced by capitulo1_single_cell.R.
# Make sure capitulo1_single_cell.R has been run and the checkpoint exists.

pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_curated.rds"))


# =============================================================================
# SECTION 14 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per curated cell type for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# Edit here: metadata column with final cell-type names.
pseudobulk_annot_col <- "celltype_curated"

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)


# =============================================================================

message("\n✓ SECTION 14 COMPLETE: Cell-type subsets created")
# SECTION 15 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# Important columns:
#   condition  = biological group used for DESeq2 comparisons
#                examples: "0N", "0.5N", "5N"
#   orig.ident = original CellRanger sample/library
#                examples: "0N", "0.5N_R1", "5N_R1"
#   replicate  = pseudo-replicate created here inside each condition
#                examples: "0N_rep1", "0N_rep2", "5N_rep3"
#
# Edit here:
#   NULL = use all condition values present in pbmc_harmony$condition
#   n_pseudoreps = pseudo-replicates per condition
pseudobulk_conditions <- NULL
n_pseudoreps          <- 3

cell_type_subsets_replicates <- assign_pseudoreplicates_batch(cell_type_subsets,
                                                             pseudobulk_conditions = pseudobulk_conditions,
                                                             n_pseudoreps = n_pseudoreps)


# QC check — replace Pavement_Cell with any cell type name from your data:
table(cell_type_subsets_replicates$Pavement_Cell$condition)
table(cell_type_subsets_replicates$Pavement_Cell$replicate)
table(cell_type_subsets_replicates$Pavement_Cell$orig.ident)


# =============================================================================

message("\n✓ SECTION 15 COMPLETE: Pseudo-replicates assigned")
# SECTION 16 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# Edit here:
#   Use condition names, not orig.ident names and not replicate names.
#   Check them with: table(cell_type_subsets_replicates$Pavement_Cell$condition)
#
#   conds = c("reference_condition", "treatment_condition")
#   log2FC > 0 means higher expression in treatment_condition
#
#   Example:
#     conds = c("0N", "5N") means log2FC = log2(5N / 0N)
comparisons <- list(
  list(conds = c("condicion1", "condicion2"), tag = "condicion1_vs_condicion2")
)

# Edit here:
#   NULL = analyze all cell types
#   c("Guard Cell", "Mesophyll") = analyze only those cell types
cell_types_to_analyze <- NULL

output_dir <- dir_06

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparisons,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_objects, "pseudobulk_replicas")
)


# =============================================================================

message("\n✓ SECTION 16 COMPLETE: Pseudobulk aggregation and DESeq2 complete")
# SECTION 17 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# Edit here:
#   volcano_tag must be one of the tag values defined in comparisons above.
#   It is not a condition name, not an orig.ident name, and not a replicate name.
#
#   Example:
#     If Section 16 has:
#       list(conds = c("0N", "5N"), tag = "0N_vs_5N")
#     then use:
#       volcano_tag <- "0N_vs_5N"
#
#   padj_cut = adjusted p-value threshold
#   lfc_cut  = absolute log2 fold-change threshold
volcano_tag <- "condicion1_vs_condicion2"
padj_cut    <- 0.05
lfc_cut     <- 1

render_volcano_plots(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag, "volcano"),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================

message("\n✓ SECTION 17 COMPLETE: Volcano plots saved")
# SECTION 18 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_prefix <- paste0("diff_table_", volcano_tag)

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================

message("\n✓ SECTION 18 COMPLETE: Differential gene tables saved")
# SECTION 19 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

# Edit here:
#   go_space = "BP", "MF", or "CC"
#   Arabidopsis: go_orgdb = org.At.tair.db | go_keytype = "TAIR"
go_space    <- "BP"
go_orgdb    <- org.At.tair.db
go_keytype  <- "TAIR"
padj_cutoff <- 0.05

go_results <- run_go_enrichment_for_contrast(
  results_dir  = file.path(dir_06, volcano_tag),
  output_dir   = file.path(dir_07, volcano_tag),
  orgdb        = go_orgdb,
  keytype      = go_keytype,
  go_space     = go_space,
  padj_cutoff  = padj_cutoff,
  contrast_tag = volcano_tag
)

# =============================================================================

message("\n✓ SECTION 19 COMPLETE: GO enrichment complete")
# SECTION 20 — LOG2FC HEATMAP
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
# Genes are ordered by the internal hierarchical dendrogram (cluster_rows = TRUE).
#
# Edit here: color scale range for log2FC values.
heatmap_limits <- c(-5, 5)

build_logfc_heatmap(
  logfc_table  = diff_tables$logfc,
  contrast_tag = volcano_tag,
  output_dir   = file.path(dir_06, volcano_tag),
  limits       = heatmap_limits
)


# =============================================================================

message("\n✓ SECTION 20 COMPLETE: Log2FC heatmap saved")
# SECTION 21 - COEXPRESSION NETWORK (hdWGCNA) BY CELL TYPE
# =============================================================================
# Builds hdWGCNA modules separately for each cell type.
# Each cell type uses its own significant DE genes from the selected contrast(s).
#
# Edit here:
#   de_contrasts_network = NULL uses all comparisons from Section 16
#   c("0.5N_vs_5N") uses only that comparison
#   cell_types_network = NULL analyzes all cell types
#   c("Guard Cell", "Mesophyll") analyzes only those cell types
#   n_metacells = metacells per celltype x sample
#   soft_power  = NULL for automatic detection, or use a number
#   max_modules = maximum number of modules shown per cell type
de_contrasts_network <- c(volcano_tag)
cell_types_network   <- NULL
n_metacells          <- 25
soft_power           <- NULL
max_modules          <- 8

de_genes_per_ct <- collect_de_genes_by_cell_type(
  seurat_obj   = pbmc_harmony,
  annot_col    = pseudobulk_annot_col,
  comparisons  = comparisons,
  de_base_dir  = dir_06,
  padj_cut     = padj_cut,
  lfc_cut      = lfc_cut,
  de_contrasts = de_contrasts_network
)

run_hdwgcna(
  seurat_obj      = pbmc_harmony,
  annot_col       = pseudobulk_annot_col,
  output_dir      = dir_08,
  cell_types      = cell_types_network,
  n_metacells     = n_metacells,
  soft_power      = soft_power,
  max_modules     = max_modules,
  gene_select     = "all",
  de_genes_per_ct = de_genes_per_ct
)

message("\n\u2713 SECTION 21 COMPLETE: hdWGCNA co-expression networks saved")


# =============================================================================
# SECTION 22 — NETWORK EXPORT & VISUALIZATION
# =============================================================================
# Reads the hdWGCNA objects from Section 21 and saves:
#   1. networks from all module genes
#   2. DE-filtered networks using only significant DE genes
#
# Edit here:
#   tom_threshold = lower gives more edges; higher gives simpler networks
#   n_hub_label = number of hub genes labelled in the plot
tom_threshold  <- 0.5
n_hub_label    <- 5
n_hub_label_de <- 10
de_dirs_network <- if (is.null(de_contrasts_network)) {
  sapply(comparisons, function(comp) file.path(dir_06, comp$tag))
} else {
  file.path(dir_06, de_contrasts_network)
}

plot_hdwgcna_network(
  hdwgcna_dir   = dir_08,
  output_dir    = dir_08,
  tom_threshold = tom_threshold,
  cell_types    = cell_types_network,
  n_hub_label   = n_hub_label,
  max_modules   = max_modules
)

filter_hdwgcna_by_de(
  hdwgcna_dir   = dir_08,
  de_dirs       = de_dirs_network,
  output_dir    = dir_08,
  padj_cut      = padj_cut,
  lfc_cut       = lfc_cut,
  n_hub_label   = n_hub_label_de,
  tom_threshold = tom_threshold,
  max_modules   = max_modules
)

message("\n✓ SECTION 22 COMPLETE: Network files and plots saved")
