# =============================================================================
# capitulo2_pseudobulk_de.R — Pseudobulk Differential Expression & GO (Part 2)
# =============================================================================
# Requires: pbmc_harmony_curated.rds generated by capitulo1_single_cell.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "~/projects2/eleo/ScRNA/metodologia/ScRNASeq-Docker/workflow/"
DATA_DIR     <- "~/projects2/eleo/ScRNA/"
base_dir     <- file.path(DATA_DIR, "metodologia/resultados")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

set.seed(1807)


# =============================================================================
# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# LOAD — CURATED OBJECT FROM PART 1
# =============================================================================
# Loads the final annotated object produced by capitulo1_single_cell.R.
# Make sure capitulo1_single_cell.R has been run and the checkpoint exists.

pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_curated.rds"))


# =============================================================================
# SECTION 14 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per curated cell type for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# ┌─ SET THE ANNOTATION COLUMN TO USE FOR PART 2 ───────────────────────────────
#   pseudobulk_annot_col : metadata column containing the final cell-type labels
# └─────────────────────────────────────────────────────────────────────────────
pseudobulk_annot_col <- "celltype_curated"

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)


# =============================================================================

message("\n✓ SECTION 14 COMPLETE: Cell-type subsets created")
# SECTION 15 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   pseudobulk_conditions : NULL = use all conditions
#                           c("0N", "0.5N") = use only those two
#   n_pseudoreps          : pseudo-replicates per condition per cell type
# └─────────────────────────────────────────────────────────────────────────────
pseudobulk_conditions <- NULL   # change to e.g. c("0.5N", "5N") to subset
n_pseudoreps          <- 3

cell_type_subsets_replicates <- assign_pseudoreplicates_batch(cell_type_subsets,
                                                             pseudobulk_conditions = pseudobulk_conditions,
                                                             n_pseudoreps = n_pseudoreps)


# QC check — replace Pavement_Cell with any cell type name from your data:
table(cell_type_subsets_replicates$Pavement_Cell$replicate)
table(cell_type_subsets_replicates$Pavement_Cell$orig.ident)


# =============================================================================

message("\n✓ SECTION 15 COMPLETE: Pseudo-replicates assigned")
# SECTION 16 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# ┌─ DEFINE YOUR CONDITION CONTRASTS HERE ──────────────────────────────────────
#   comparisons : each entry must contain
#                   conds = c("reference", "treatment")
#                   tag   = output folder / file label
#
#   log2FC interpretation:
#     positive → gene is upregulated in treatment vs reference
#     negative → gene is upregulated in reference vs treatment
#
#   Example: conds = c("0.5N", "5N")  →  log2FC = log2(5N / 0.5N)
# └─────────────────────────────────────────────────────────────────────────────
comparisons <- list(
  list(conds = c("0.5N", "5N"), tag = "0.5N_vs_5N"),
  list(conds = c("0N",   "5N"), tag = "0N_vs_5N")
)

# ┌─ SELECT WHICH CELL TYPES TO ANALYZE ────────────────────────────────────────
#   NULL = analyze all cell types
#   c("Epidermis", "Cortex") = analyze only these
# └─────────────────────────────────────────────────────────────────────────────
cell_types_to_analyze <- NULL  # Change to c("Epidermis", "Cortex") to filter

output_dir <- dir_06

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparisons,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_objects, "pseudobulk_replicas")
)


# =============================================================================

message("\n✓ SECTION 16 COMPLETE: Pseudobulk aggregation and DESeq2 complete")
# SECTION 17 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# ┌─ VOLCANO PARAMETERS ─────────────────────────────────────────────────────────
#   volcano_tag : tag of the contrast to visualize (must match comparisons)
#   padj_cut    : adjusted p-value threshold
#   lfc_cut     : absolute log2 fold-change threshold
# └─────────────────────────────────────────────────────────────────────────────
volcano_tag <- "0.5N_vs_5N"
padj_cut    <- 0.05
lfc_cut     <- 1

render_volcano_plots(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag, "volcano"),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================

message("\n✓ SECTION 17 COMPLETE: Volcano plots saved")
# SECTION 18 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_prefix <- paste0("diff_table_", volcano_tag)

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================

message("\n✓ SECTION 18 COMPLETE: Differential gene tables saved")
# SECTION 19 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

# ┌─ CHANGE FOR YOUR ORGANISM ────────────────────────────────────────────────
#   Arabidopsis: go_orgdb = org.At.tair.db  |  go_keytype = "TAIR"
#   Human:       go_orgdb = org.Hs.eg.db    |  go_keytype = "ENSEMBL"
#   Mouse:       go_orgdb = org.Mm.eg.db    |  go_keytype = "ENSEMBL"
# └─────────────────────────────────────────────────────────────────────────
go_space    <- "BP"   # "MF" (function) or "CC" (component)
go_orgdb    <- org.At.tair.db
go_keytype  <- "TAIR"
padj_cutoff <- 0.05

deseq2_files <- list.files(file.path(dir_06, volcano_tag),
                           pattern = "^DESeq2_.*\\.csv$",
                           full.names = TRUE)

for (deseq2_file in deseq2_files) {
  cell_type <- gsub("^DESeq2_|\\.csv$", "", basename(deseq2_file))

  deseq2_results <- read.csv(deseq2_file, row.names = 1)
  sig_genes <- rownames(deseq2_results)[deseq2_results$padj < padj_cutoff]

  if (length(sig_genes) > 0) {
    run_simple_go_enrichment(
      diff_table = data.frame(gene_id = sig_genes),
      output_dir = file.path(dir_07, volcano_tag),
      orgdb        = go_orgdb,
      keytype      = go_keytype,
      go_space = go_space,
      padj_cutoff = padj_cutoff,
      cell_type = cell_type,
      contrast_tag = volcano_tag
    )
  }
}

# =============================================================================

message("\n✓ SECTION 19 COMPLETE: GO enrichment complete")
# SECTION 20 — LOG2FC HEATMAP + CLUSTERING
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
#
# ┌─ PARAMETERS ─────────────────────────────────────────────────────────────────
#   CLUSTER_METHOD   : clustering method for grouping DE genes
#     "hclust" — hierarchical (euclidean + cutreeDynamic) — numbered clusters (1,2,3...)
#                fast, good starting point; increase min_cluster_size if too many small clusters
#     "wgcna"  — coexpression network (TOM) — named clusters (turquoise, blue...)
#                slower, captures co-regulation patterns
#   heatmap_limits   : color scale range for log2FC values
#   min_cluster_size : minimum genes per cluster — hclust only (default 10)
#   wgcna_merge_cut  : merge close WGCNA modules — wgcna only (default 0.25)
# └─────────────────────────────────────────────────────────────────────────────
CLUSTER_METHOD   <- "hclust"  # "hclust" or "wgcna"
heatmap_limits   <- c(-5, 5)
min_cluster_size <- 100       # hclust only — increase to get fewer, larger clusters
wgcna_merge_cut  <- 0.25     # wgcna only

heatmap_results <- build_logfc_heatmap(
  logfc_table      = diff_tables$logfc,
  contrast_tag     = volcano_tag,
  output_dir       = file.path(dir_06, volcano_tag),
  method           = CLUSTER_METHOD,
  limits           = heatmap_limits,
  min_cluster_size = min_cluster_size,
  merge_cut        = wgcna_merge_cut
)


# =============================================================================

message("\n✓ SECTION 20 COMPLETE: Log2FC heatmap and clustering complete")
# SECTION 21 — GO ENRICHMENT PER CLUSTER
# =============================================================================
# Runs GO enrichment for each cluster identified in Section 20.
# Uses go_orgdb and go_keytype defined in Section 19 — change them there.
# Uses the cluster assignments from heatmap_results.

go_clusters_padj <- 0.05  # adjusted p-value threshold for GO enrichment per cluster

for (clust_id in unique(heatmap_results$cluster)) {
  genes <- heatmap_results$gene_id[heatmap_results$cluster == clust_id]

  run_simple_go_enrichment(
    diff_table   = data.frame(gene_id = genes),
    output_dir   = file.path(dir_06, volcano_tag, paste0("GO_clusters_", CLUSTER_METHOD)),
    orgdb        = go_orgdb,
    keytype      = go_keytype,
    go_space     = "BP",
    padj_cutoff  = go_clusters_padj,
    cell_type    = as.character(clust_id),
    contrast_tag = volcano_tag
  )
}


# =============================================================================

message("\n✓ SECTION 21 COMPLETE: GO enrichment per cluster complete")
# SECTION 22 — NETWORK INFERENCE PER CLUSTER
# =============================================================================
# Identifies which transcription factors (TFs) regulate the genes in each
# cluster from Section 20. Results are a ranked hypothesis list.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   NETWORK_METHOD : "GENIE3" — recommended for small datasets (n < 15 samples)
#                    "WGCNA"  — for comparison only; unreliable with n < 15
#   n_top_clusters :  3    — top 3 largest clusters (default, faster)
#                    NULL — all clusters
#   n_cores        : parallel cores (adjust to your machine)
#
#   cor_min  ★ ADJUST THIS to control how many TF→gene edges are reported:
#     Only TF→gene pairs where expression is correlated with Pearson |r| ≥ cor_min
#     are kept. Lower values = more edges (exploratory); higher = fewer but more
#     reliable. Start at 0.70 and raise if the resulting network looks too dense.
# └─────────────────────────────────────────────────────────────────────────────
NETWORK_METHOD <- "GENIE3"  # "GENIE3" or "WGCNA"
n_top_clusters <- NULL       # NULL = all clusters, or e.g. 3 for the 3 largest
n_cores        <- 4          # adjust to your machine
cor_min        <- 0.70       # ★ see table above — start here, raise if too noisy

if (NETWORK_METHOD == "WGCNA")
  message("\n⚠ WGCNA: unreliable with n < 15 samples — results are comparative only.")

net_pipeline <- run_network_inference_pipeline(
  heatmap_results  = heatmap_results,          # clusters from Section 20
  pseudobulk_dir   = file.path(dir_objects, "pseudobulk_replicas"),
  output_base_dir  = file.path(dir_08, volcano_tag),
  methods          = c(NETWORK_METHOD),         # "GENIE3" or "WGCNA"
  orgdb            = go_orgdb,                  # organism DB (set in Section 19)
  keytype          = go_keytype,                # gene ID type (set in Section 19)
  custom_tfs       = NULL,                      # NULL = auto-detect TFs from orgdb
  cor_min          = cor_min,                    # threshold set above
  genie3_ntrees    = 500,                       # Random Forest trees per gene
  n_cores          = n_cores,                   # parallel cores
  soft_power       = 18,                        # WGCNA only
  network_type     = "signed",                  # WGCNA only
  tom_threshold    = 0.05,                      # WGCNA only
  n_top_clusters   = n_top_clusters,            # largest clusters to analyze
  min_var_filter   = 0.01                       # drop near-constant genes
)

network_results <- net_pipeline$results[[NETWORK_METHOD]]
message("\n✓ SECTION 22 COMPLETE: Network inference complete")


# =============================================================================
# SECTION 23 — NETWORK VISUALIZATION (FORCE-DIRECTED LAYOUT)
# =============================================================================
# Draws TF → target edges as a force-directed graph for each cluster.
# Node size = number of connections; edge width = importance score.
# Uses the method and results from Section 22 automatically.

visualize_network_per_cluster(
  network_results     = network_results,
  cluster_assignments = heatmap_results,
  output_dir          = file.path(dir_08, volcano_tag, "VISUALIZATION"),
  method_name         = NETWORK_METHOD
)

message("\n✓ SECTION 23 COMPLETE: Network visualization saved")


# =============================================================================
# SECTION 24 — CLUSTER PROFILE REPORTS
# =============================================================================
# Per-cluster profiles: heatmaps, expression statistics, functional annotation.
#
# For each cluster from SEC 20:
#   • Expression heatmap (pseudobulk × genes, with row clustering)
#   • Expression statistics (mean, SD, range)
#   • Gene count and composition
#
# Links to GO enrichment results from SEC 21 for functional context.

exprMatr_pseudobulk <- load_pseudobulk_matrix(
  file.path(dir_objects, "pseudobulk_replicas"),
  normalize = TRUE
)

generate_cluster_profile_report(
  cluster_assignments = heatmap_results,
  pseudobulk_matrix   = exprMatr_pseudobulk,
  output_dir          = file.path(dir_06, volcano_tag, "CLUSTER_PROFILES"),
  method_name         = CLUSTER_METHOD
)

message("\n✓ SECTION 24 COMPLETE: Cluster profiles saved")




