# =============================================================================
# capitulo3_pseudotime.py - Pseudotime trajectory analysis (Part 3)
# =============================================================================
# Requires: pbmc_harmony_curated.h5ad generated by capitulo1_single_cell.R
#
# How to use:
#   1. Run sections in order.
#   2. Edit only the small parameter blocks marked "Edit here".
#   3. All plots are saved as 18 x 18.
# =============================================================================


# %%
# =============================================================================
# SECTION 23 - SETUP
# =============================================================================
# Sets paths and loads Python libraries/functions.
# Change PIPELINE_DIR and DATA_DIR only if your folder structure is different.

import os

PIPELINE_DIR = "/workspace/SingleCell/workflow"
DATA_DIR     = "/workspace/."
base_dir     = os.path.join(DATA_DIR, "resultados")

exec(open(os.path.join(PIPELINE_DIR, "load_libraries_python.py")).read(), globals())
exec(open(os.path.join(PIPELINE_DIR, "ScRNA_Pseudotime_Functions.py")).read(), globals())

dir_pseudotime = os.path.join(base_dir, "09_pseudotime")
os.makedirs(dir_pseudotime, exist_ok=True)

print("SECTION 23 COMPLETE: Setup done")


# %%
# =============================================================================
# SECTION 24 - LOAD CURATED OBJECT
# =============================================================================
# Loads the AnnData object exported from capitulo1.
#
# What this section does:
#   1. Reads the .h5ad object with cells, genes and metadata.
#   2. Converts Seurat-style UMAP/PCA/HARMONY coordinates to scanpy names.
#   3. Prints available cell types for Section 25.
#   4. Saves overview UMAP plots.
#
# Edit here:
#   INPUT_H5AD     = curated .h5ad from capitulo1
#   ANNOTATION_COL = metadata column with final cell-type labels
#   N_JOBS         = CPU cores for parallel Python steps

INPUT_H5AD     = os.path.join("/workspace/resultados/objects/pbmc_harmony_curated.h5ad")
ANNOTATION_COL = "celltype_curated"
N_JOBS         = 4

adata, N_JOBS = load_curated_object(
    input_h5ad     = INPUT_H5AD,
    dir_pseudotime = dir_pseudotime,
    annotation_col = ANNOTATION_COL,
    n_jobs         = N_JOBS,
)


# %%
# =============================================================================
# SECTION 25 - CELL TYPE SELECTION
# =============================================================================
# Selects the cell types used to build the trajectory.
#
# Edit here:
#   Copy names exactly from the Section 24 list.

TRAJECTORY_CLUSTERS = ["epidermis", "guard cell"]

adata_sub = preview_trajectory_selection(
    adata          = adata,
    clusters       = TRAJECTORY_CLUSTERS,
    annotation_col = ANNOTATION_COL,
    dir_pseudotime = dir_pseudotime,
)


# %%
# =============================================================================
# SECTION 26 - TRAJECTORY INFERENCE
# =============================================================================
# Builds one or more trajectory runs using the selected cell types.
#
# Edit here:
#   ROOT_CLUSTER = biological start point where pseudotime = 0
#   Add more trajectory_run(...) lines to test more parameter sets.
#
# Parameter meaning:
#   nodes        = more nodes gives a finer tree
#   sigma        = lower values follow the cells more tightly
#   lambda_value = higher values make a simpler tree
#   eigs         = diffusion-map dimensions used for trajectory geometry
#   seed         = reproducibility

ROOT_CLUSTER = "epidermis"

TRAJECTORY_RUNS = [
    trajectory_run(nodes=50, sigma=0.1, lambda_value=200, eigs=8, seed=3),
]

adata_traj, selected_trajectory_dir, trajectory_runs = run_trajectory_runs(
    adata           = adata,
    clusters        = TRAJECTORY_CLUSTERS,
    root_cluster    = ROOT_CLUSTER,
    annotation_col  = ANNOTATION_COL,
    output_base_dir = dir_pseudotime,
    runs            = TRAJECTORY_RUNS,
)


# %%
# =============================================================================
# SECTION 27 - PLOT GENES ON TRAJECTORY
# =============================================================================
# Plots the selected genes on the trajectory layout.
#
# Edit here:
#   Write the gene IDs you want to visualize.

GENES = ["AT1G22690", "AT4G04890", "AT1G80070"]
name  = os.path.basename(selected_trajectory_dir)

if adata_traj.X is None and "logcounts" in adata_traj.layers:
    adata_traj.X = adata_traj.layers["logcounts"]

gene_plots_dir = os.path.join(selected_trajectory_dir, "gene_plots")
os.makedirs(gene_plots_dir, exist_ok=True)

fig = sc.pl.draw_graph(
    adata_traj,
    color      = GENES,
    title      = GENES,
    show       = False,
    return_fig = True,
)
save_plot_18x18(fig, os.path.join(gene_plots_dir, f"{name}_gene_plots.png"))
save_plot_18x18(fig, os.path.join(gene_plots_dir, f"{name}_gene_plots.pdf"))
plt.close(fig)

print("SECTION 27 COMPLETE: Gene trajectory plots saved")


# %%
# =============================================================================
# SECTION 28 - GENE TRENDS
# =============================================================================
# Saves two heatmaps:
#   1. Top variable genes along the trajectory.
#   2. Custom genes highlighted by the user.
#
# Edit here:
#   TOP_N           = number of top genes to highlight in the first plot
#   HIGHLIGHT_GENES = genes of interest to highlight in the second plot
#   ORDERING        = "max", "pearson", or "quantile"

TOP_N           = 10
HIGHLIGHT_GENES = ["AT1G22690", "AT4G04890", "AT1G80070"]
ORDERING        = "max"
# Lower this (e.g. 3) if you hit "fewer unique covariate combinations than
# specified maximum degrees of freedom" during test_association.
SPLINE_DF       = 3

top_path, highlight_path = run_step29_gene_trends(
    adata        = adata_traj,
    run_dir      = selected_trajectory_dir,
    name         = os.path.basename(selected_trajectory_dir),
    custom_genes = HIGHLIGHT_GENES,
    top_n        = TOP_N,
    ordering     = ORDERING,
    n_jobs       = N_JOBS,
    spline_df    = SPLINE_DF,
)

print("SECTION 28 COMPLETE: Gene trend plots saved")


# %%
# =============================================================================
# CAPITULO 3 COMPLETE
# =============================================================================
print("CAPITULO 3 COMPLETE")
