#!/home/mvergara/projects3/app/miniconda/envs/scrna_seba/bin/python
# =============================================================================
# capitulo3_pseudotime.py — Pseudotime Trajectory Analysis (Part 3)
# =============================================================================
# Requires: pbmc_harmony_curated.h5ad generated by capitulo1_single_cell.R
# Covers: trajectory inference, pseudotime, milestone gene analysis, trends.
#
# Python environment: scrna_seba
#   Shebang above sets the interpreter automatically when run as a script.
#   To run interactively, activate the environment first:
#     conda activate scrna_seba
# =============================================================================

import os

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────
PIPELINE_DIR = os.path.expanduser("~/projects2/eleo/ScRNA/metodologia/ScRNASeq-Docker/")
DATA_DIR     = os.path.expanduser("~/projects2/eleo/ScRNA/")
base_dir     = os.path.join(DATA_DIR, "metodologia/resultados")

# Load libraries and functions (equivalent to source() in R)
exec(open(os.path.join(PIPELINE_DIR, "load_libraries_python.py")).read(), globals())
exec(open(os.path.join(PIPELINE_DIR, "ScRNA_Pseudotime_Functions.py")).read(), globals())

# Output directories
dir_objects    = os.path.join(base_dir, "objects")
dir_pseudotime = os.path.join(base_dir, "09_pseudotime")
os.makedirs(dir_pseudotime, exist_ok=True)


# =============================================================================
# SECTION 25 — LOAD DATA
# =============================================================================
# Loads the curated AnnData object exported by capitulo1_single_cell.R.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   INPUT_H5AD     : path to the .h5ad file from capitulo1
#                    (should be in the objects/ folder)
#
#   ANNOTATION_COL ★ MOST IMPORTANT PARAMETER
#                    Column in adata.obs with your final cell type labels.
#                    Run this to see what columns are available:
#                      print(adata.obs.columns.tolist())
#                    Common choices:
#                      "celltype_curated"          — your manually curated labels
#                      "celltype_reference"         — labels from automatic annotation
#                      "seurat_clusters"            — raw cluster numbers (no biology)
#
#   N_JOBS         : CPU cores for parallel steps
#                    Use 4–8 on a laptop, up to 32 on a server
# └─────────────────────────────────────────────────────────────────────────────
INPUT_H5AD     = os.path.join(dir_objects, "pbmc_harmony_curated.h5ad")
ANNOTATION_COL = "celltype_curated"  # ★ change to your cell type column
N_JOBS         = 4                   # ★ adjust to your machine

adata = sc.read_h5ad(INPUT_H5AD)

# Keys exported from R (Seurat) need to be mapped to scanpy conventions
adata.obsm["X_umap"] = adata.obsm["UMAP"].values
adata.obsm["X_pca"]  = adata.obsm["PCA"].values

sc.settings.figdir = dir_pseudotime
sc.set_figure_params(figsize=(10, 10), dpi=300, dpi_save=300)

# Inspect available cell types — use these names in SECTION 26
print("Available cell types in", ANNOTATION_COL, ":")
print(sorted(adata.obs[ANNOTATION_COL].unique().tolist()))

sc.pl.umap(adata, color=ANNOTATION_COL, save="_overview.png")

print("\n✓ SECTION 25 COMPLETE: Data loaded")


# =============================================================================
# SECTION 26 — TRAJECTORY INFERENCE
# =============================================================================
# Builds a tree-shaped trajectory through the selected cell types using
# Palantir diffusion maps + scFates ElPiGraph (PPT method).
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   TRAJECTORY_CLUSTERS : cell types to include in the trajectory
#                         ★ Use 2–4 related types (progenitor → mature)
#                         ★ Names must exactly match values in ANNOTATION_COL
#
#   ROOT_CLUSTER        : cell type where pseudotime = 0
#                         ★ Use the least-differentiated (progenitor) type
#
#   NODES               : tree resolution (50–200)
#                         more nodes = finer branch detail, slower
#
#   SIGMA               : tree smoothing (0.1–0.5)
#                         lower = tree follows individual cells more tightly
#
#   PPT_LAMBDA          : complexity penalty (10–200)
#                         higher = simpler tree with fewer branches
#
#   N_EIGS              : diffusion map dimensions to keep (must be < 50)
#                         more = captures finer structure, but noisier
# └─────────────────────────────────────────────────────────────────────────────
TRAJECTORY_CLUSTERS = ["Pavement Cell", "Guard Cell", "Meristemoid"]  # ★ adjust
ROOT_CLUSTER        = "Meristemoid"   # ★ progenitor / starting cell type
NODES               = 150
SIGMA               = 0.2
PPT_LAMBDA          = 60
N_EIGS              = 20              # must be < 50

adata_traj = build_pseudotime_trajectory(
    adata          = adata,
    clusters       = TRAJECTORY_CLUSTERS,
    root_cluster   = ROOT_CLUSTER,
    annotation_col = ANNOTATION_COL,
    nodes          = NODES,
    sigma          = SIGMA,
    ppt_lambda     = PPT_LAMBDA,
    n_eigs         = N_EIGS,
    n_components   = 50,
    n_neighbors    = 50,
    seed           = 3,
)

plot_trajectory_graphs(
    adata          = adata_traj,
    name           = "trajectory",
    output_dir     = os.path.join(dir_pseudotime, "trajectory"),
    annotation_col = ANNOTATION_COL,
)

print("\n✓ SECTION 26 COMPLETE: Trajectory built and saved")


# =============================================================================
# SECTION 27 — DENDROGRAM AND MILESTONES
# =============================================================================
# Adds a dendrogram to the trajectory and identifies branch endpoints
# (milestones). Each milestone represents a differentiation endpoint.
#
# After running this section, inspect the milestone names printed below —
# you will need them to configure SECTION 28.

adata_traj = build_dendrogram(adata_traj)

# ★ Read these milestone names and use them in SECTION 28
print("Available milestones:")
print(sorted(adata_traj.obs["milestones"].unique().tolist()))

scf.pl.dendrogram(
    adata_traj,
    color          = "milestones",
    legend_loc     = "on data",
    save           = "_milestones.pdf",
)

print("\n✓ SECTION 27 COMPLETE: Dendrogram built — see milestone names above")


# =============================================================================
# SECTION 28 — MILESTONE ANALYSIS
# =============================================================================
# For each branch endpoint: tests which genes change significantly along
# that branch and fits smooth expression curves over pseudotime.
# Saves intermediate checkpoints (*_fitted.h5ad) for Section 29.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   MILESTONES_TO_ANALYZE : list of milestone names to analyze
#                           ★ Run Section 27 first to see available names
#                           ★ Analyze only the biologically relevant endpoints
#
#   A_CUT                 : association strength threshold (0–1)
#                           lower = more genes retained (noisier)
#                           higher = fewer genes (more selective)
#                           recommended starting value: 0.3
#
#   P_VAL_CUT             : significance threshold for gene-pseudotime test
# └─────────────────────────────────────────────────────────────────────────────
MILESTONES_TO_ANALYZE = ["Guard_Cell", "Pavement_1"]  # ★ adjust after Section 27
A_CUT     = 0.3
P_VAL_CUT = 0.001

fitted_objects = {}

for milestone in MILESTONES_TO_ANALYZE:
    fitted_objects[milestone] = run_milestone_analysis(
        adata         = adata_traj,
        milestone     = milestone,
        root_milestone= ROOT_CLUSTER,
        output_dir    = os.path.join(dir_pseudotime, "milestones"),
        n_jobs        = N_JOBS,
        a_cut         = A_CUT,
        p_val_cut     = P_VAL_CUT,
        name_file     = "pseudotime",
    )

print("\n✓ SECTION 28 COMPLETE: Milestone analysis done")


# =============================================================================
# SECTION 29 — GENE EXPRESSION TRENDS
# =============================================================================
# For each milestone: generates a heatmap of the top dynamically expressed
# genes along that branch. Also exports a ranked CSV table.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   HIGHLIGHT_GENES : known marker genes to highlight in the heatmap
#                     ★ Use gene IDs matching your organism
#                       (TAIR IDs for Arabidopsis, e.g. "AT3G24140")
#                     ★ Leave as [] if you have no prior markers
# └─────────────────────────────────────────────────────────────────────────────
HIGHLIGHT_GENES = []  # ★ e.g. ["AT5G53210", "AT3G06120", "AT3G24140"]

for milestone, adata_fitted in fitted_objects.items():
    plot_gene_trends(
        adata_fitted    = adata_fitted,
        milestone_name  = milestone,
        output_dir      = os.path.join(dir_pseudotime, "trends"),
        highlight_genes = HIGHLIGHT_GENES,
    )
    genes_by_pseudotime_peak(
        adata          = adata_fitted,
        milestone_name = milestone,
        output_dir     = os.path.join(dir_pseudotime, "tables"),
    )

print("\n✓ SECTION 29 COMPLETE: Gene trends and tables saved")


# =============================================================================
# SECTION 30 — MODULE SCORES  [OPTIONAL]
# =============================================================================
# Projects user-defined gene lists onto the trajectory as a per-cell score.
# Useful for validating published gene modules or overlaying known signatures.
# Skip this section entirely if you do not have custom gene lists.
#
# ┌─ PARAMETERS ────────────────────────────────────────────────────────────────
#   MODULE_GENE_FILES : dict of {label: path_to_file}
#                       ★ Each file should be tab-separated with a gene ID column
#                       ★ Leave as {} to skip this section
#
#   MODULE_ID_COL     : column in each file that contains gene IDs
#                       ★ For Arabidopsis: usually "ID" or "TAIR"
#                       ★ For human/mouse: usually "gene_id" or "symbol"
# └─────────────────────────────────────────────────────────────────────────────
MODULE_GENE_FILES = {}    # ★ e.g. {"cluster1": "/path/to/cluster1_genes.txt"}
MODULE_ID_COL     = "ID"  # ★ column with gene IDs in each file

if MODULE_GENE_FILES:
    for label, fpath in MODULE_GENE_FILES.items():
        df        = pd.read_csv(fpath, sep="\t")
        gene_list = df[MODULE_ID_COL].dropna().unique().tolist()
        compute_module_score(adata_traj, gene_list, label)

    sc.pl.draw_graph(
        adata_traj,
        color  = [f"{label}_module_score" for label in MODULE_GENE_FILES],
        cmap   = "viridis",
        show   = False,
        save   = "_module_scores.png",
    )
    print("✓ Module score plots saved")

print("\n✓ SECTION 30 COMPLETE: Module scores done")
