# =============================================================================
# capitulo2_wt_pifq.R — Pseudobulk Differential Expression & GO (WT vs pifq)
# =============================================================================
# Requires: pbmc_harmony_annotated.rds generated by capitulo1_wt_pifq.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "/workspace/SingleCell/workflow"
DATA_DIR     <- "/workspace/."
base_dir     <- file.path(DATA_DIR, "resultados_wt")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

set.seed(1807)


# =============================================================================
# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# LOAD — ANNOTATED OBJECT FROM PART 1
# =============================================================================
# Loads the bibliography-annotated object produced by capitulo1_wt_pifq.R.
# This WT/pifq version uses pbmc_harmony$celltype directly.

pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_annotated.rds"))


# =============================================================================
# SECTION 13 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per celltype label for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# Edit here: metadata column with direct bibliography cell-type labels.
pseudobulk_annot_col <- "celltype"

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)

celltype_counts <- summarize_pseudobulk_celltype_counts(
  pbmc_harmony,
  annot_col = pseudobulk_annot_col,
  output_file = file.path(dir_objects, "pseudobulk_celltype_counts.tsv")
)


# =============================================================================

message("\n✓ SECTION 13 COMPLETE: Cell-type subsets created")
# SECTION 14 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# Important columns:
#   condition  = biological group used for DESeq2 comparisons
#                examples: "0N", "0.5N", "5N"
#   orig.ident = original CellRanger sample/library
#                examples: "0N", "0.5N_R1", "5N_R1"
#   replicate  = pseudo-replicate created here inside each condition
#                examples: "0N_rep1", "0N_rep2", "5N_rep3"
#
# Edit here:
#   NULL = use all condition values present in pbmc_harmony$condition
#   n_pseudoreps = pseudo-replicates per condition
pseudobulk_conditions <- c("WT", "pifq")
n_pseudoreps          <- 3

cell_type_subsets_replicates <- assign_pseudoreplicates_batch(
  cell_type_subsets,
  pseudobulk_conditions = pseudobulk_conditions,
  n_pseudoreps = n_pseudoreps
)


# QC check — replace Mesophyll with any cell type name from your data:
table(cell_type_subsets_replicates$Mesophyll$condition)
table(cell_type_subsets_replicates$Mesophyll$replicate)
table(cell_type_subsets_replicates$Mesophyll$orig.ident)

pseudoreplicate_counts <- summarize_pseudoreplicate_counts(
  cell_type_subsets_replicates,
  output_file = file.path(dir_objects, "pseudobulk_pseudoreplicate_counts.tsv")
)


# =============================================================================

message("\n✓ SECTION 14 COMPLETE: Pseudo-replicates assigned")
# SECTION 15 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# Edit here:
#   Use condition names, not orig.ident names and not replicate names.
#   Check them with: table(cell_type_subsets_replicates$Mesophyll$condition)
#
#   conds = c("reference_condition", "treatment_condition")
#   log2FC > 0 means higher expression in treatment_condition
#
#   Example:
#     conds = c("0N", "5N") means log2FC = log2(5N / 0N)
comparisons <- list(
  list(conds = c("WT", "pifq"), tag = "WT_vs_pifq")
)

# Edit here:
#   NULL = analyze all cell types
#   c("Guard Cell", "Mesophyll") = analyze only those cell types
cell_types_to_analyze <- NULL

output_dir <- dir_06

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparisons,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_objects, "pseudobulk_replicas")
)


# =============================================================================

message("\n✓ SECTION 15 COMPLETE: Pseudobulk aggregation and DESeq2 complete")
# SECTION 16 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# Edit here:
#   volcano_tag must be one of the tag values defined in comparisons above.
#   It is not a condition name, not an orig.ident name, and not a replicate name.
#
#   Example:
#     If Section 15 has:
#       list(conds = c("0N", "5N"), tag = "0N_vs_5N")
#     then use:
#       volcano_tag <- "0N_vs_5N"
#
#   padj_cut = adjusted p-value threshold
#   lfc_cut  = absolute log2 fold-change threshold
volcano_tag <- "WT_vs_pifq"
padj_cut    <- 0.05
lfc_cut     <- 1

render_volcano_plots(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag, "volcano"),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================

message("\n✓ SECTION 16 COMPLETE: Volcano plots saved")
# SECTION 17 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_prefix <- paste0("diff_table_", volcano_tag)

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================

message("\n✓ SECTION 17 COMPLETE: Differential gene tables saved")
# SECTION 18 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

# Edit here:
#   go_space = "BP", "MF", or "CC"
#   Arabidopsis: go_orgdb = org.At.tair.db | go_keytype = "TAIR"
go_space    <- "BP"
go_orgdb    <- org.At.tair.db
go_keytype  <- "TAIR"
padj_cutoff <- 0.05

go_results <- run_go_enrichment_for_contrast(
  results_dir  = file.path(dir_06, volcano_tag),
  output_dir   = file.path(dir_07, volcano_tag),
  orgdb        = go_orgdb,
  keytype      = go_keytype,
  go_space     = go_space,
  padj_cutoff  = padj_cutoff,
  contrast_tag = volcano_tag
)

# =============================================================================

message("\n✓ SECTION 18 COMPLETE: GO enrichment complete")
# SECTION 19 — LOG2FC HEATMAP
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
# Genes are ordered by the row dendrogram. Cell-type columns are NOT clustered:
# they follow the same marker-table order used by the Section 7 dotplot.
#
# Edit here: color scale range for log2FC values.
heatmap_limits <- c(-5, 5)
heatmap_marker_file <- file.path(DATA_DIR, "biblio_marks_custom.txt")

build_logfc_heatmap(
  logfc_table  = diff_tables$logfc,
  contrast_tag = volcano_tag,
  output_dir   = file.path(dir_06, volcano_tag),
  limits       = heatmap_limits,
  marker_file  = heatmap_marker_file
)


# =============================================================================

message("\n✓ SECTION 19 COMPLETE: Log2FC heatmap saved")
# SECTION 20 - COEXPRESSION TOM NETWORK (hdWGCNA) ON SIGNIFICANT GENES
# =============================================================================
# Builds one hdWGCNA TOM network using the complete significant-gene subset
# from the log2FC heatmap table created in Section 19. Internal grouping
# diagnostics are intentionally not exported; the final visualization uses DE direction
# (up/down/mixed) in Section 21b.
#
# Edit here:
#   n_metacells = metacells per celltype x sample
#   soft_power  = NULL for automatic detection, or use a number
wgcna_name  <- "unified"
n_metacells     <- 50
soft_power      <- NULL

run_unified_hdwgcna(
  seurat_obj      = pbmc_harmony,
  de_table_path   = file.path(dir_06, volcano_tag, "tabla_log2FC_fc1_padj_005.tsv"),
  output_dir      = dir_08,
  annot_col       = pseudobulk_annot_col,
  sample_col      = "orig.ident",
  wgcna_name      = wgcna_name,
  n_metacells     = n_metacells,
  soft_power      = soft_power
)

message("\n\u2713 SECTION 20 COMPLETE: hdWGCNA TOM network saved")


# =============================================================================
# SECTION 21 — TOM EDGE EXPORT
# =============================================================================
# Reads the unified hdWGCNA object from Section 20 and saves TOM edges for the
# DE-direction network in Section 21b. No internal-grouping network figure is made.
#
# Edit here:
#   tom_threshold = lower gives more edges; higher gives simpler networks
tom_threshold <- 0.2

export_hdwgcna_tom_edges(
  hdwgcna_dir   = dir_08,
  output_dir    = dir_08,
  tom_threshold = tom_threshold,
  wgcna_name    = wgcna_name
)

message("\n✓ SECTION 21 COMPLETE: TOM edge table saved")

# =============================================================================
# SECTION 21b — TF CO-EXPRESSION NETWORK (DE-direction coloring)
# =============================================================================
# Filters the hdWGCNA edges to TF-containing pairs using AtTFDB locus list
# (downloaded from https://agris-knowledgebase.org/AtTFDB/download_csv).
# Nodes colored by DE direction: up (red), down (blue), mixed (grey).
# TFs drawn as triangles; co-expression partners as circles.
#
# Edit here:
#   tom_threshold_tf = TOM weight cutoff for TF network
#   n_hub_label_tf   = number of top hub TFs to label
tom_threshold_tf <- 0.2
n_hub_label_tf   <- 15

edges_all <- read.table(file.path(dir_08, "edges_unified.tsv"),
                        header=TRUE, sep="\t")
tfs       <- trimws(readLines(file.path(DATA_DIR, "SingleCell", "data", "AtTFDB_loci.txt")))
de_mat    <- read.table(
  file.path(dir_06, volcano_tag, "tabla_log2FC_fc1_padj_005.tsv"),
  header=TRUE, sep="\t", row.names=1, check.names=FALSE)

edges_tf <- edges_all[edges_all$weight >= tom_threshold_tf, ]
net_tf   <- build_tf_network(edges_tf, tfs, de_mat)
plot_tf_de_network(net_tf,
                   output_dir    = dir_08,
                   layout        = "graphopt",
                   n_hub_label   = n_hub_label_tf,
                   contrast_tag  = volcano_tag,
                   output_pdf    = "network_tf_DE_direction.pdf",
                   output_width  = 22,
                   output_height = 22)

message("\n✓ SECTION 21b COMPLETE: TF network saved to network_tf_DE_direction.pdf")
