# =============================================================================
# capitulo2_pseudobulk_de.R — Pseudobulk Differential Expression & GO (Part 2)
# =============================================================================
# Requires: pbmc_harmony_curated.rds generated by capitulo1_single_cell.R
# Covers pseudobulk DE (DESeq2), volcano plots, GO enrichment,
#         log2FC heatmaps, and network inference.
# =============================================================================

# ── Configuration (must match capitulo1_single_cell.R) ───────────────────────────────
PIPELINE_DIR <- "/workspace/workflow_nuevo"
DATA_DIR     <- "/workspace/."
base_dir     <- file.path(DATA_DIR, "resultados")

source(file.path(PIPELINE_DIR, "load_libraries.R"))
source(file.path(PIPELINE_DIR, "custom_seurat.R"))
source(file.path(PIPELINE_DIR, "ScRNA_Analysis_Functions.R"))

list2env(create_pipeline_dirs(base_dir), envir = .GlobalEnv)  # creates output folders and loads their paths as variables

set.seed(1807)


# =============================================================================
# ████████████████████████  PART 2 — PSEUDOBULK DE & GO  ██████████████████████
# =============================================================================


# =============================================================================
# LOAD — CURATED OBJECT FROM PART 1
# =============================================================================
# Loads the final annotated object produced by capitulo1_single_cell.R.
# Make sure capitulo1_single_cell.R has been run and the checkpoint exists.

pbmc_harmony <- readRDS(file.path(dir_objects, "pbmc_harmony_curated.rds"))


# =============================================================================
# SECTION 14 — CELL-TYPE SUBSETS
# =============================================================================
# Creates one Seurat subset per curated cell type for downstream pseudobulk
# analysis. Object names are sanitised so they can be used safely as list names
# and output filenames.
#
# Edit here: metadata column with final cell-type names.
pseudobulk_annot_col <- "celltype_curated"

# Create cell-type subsets for pseudobulk analysis
cell_type_subsets <- create_cell_type_subsets(pbmc_harmony, annot_col = pseudobulk_annot_col)


# =============================================================================

message("\n✓ SECTION 14 COMPLETE: Cell-type subsets created")
# SECTION 15 — PSEUDO-REPLICATE ASSIGNMENT
# =============================================================================
# Assigns random pseudo-replicates within each condition for every cell type.
# Only subsets containing at least two conditions are kept for Part 2.
#
# Important columns:
#   condition  = biological group used for DESeq2 comparisons
#                examples: "0N", "0.5N", "5N"
#   orig.ident = original CellRanger sample/library
#                examples: "0N", "0.5N_R1", "5N_R1"
#   replicate  = pseudo-replicate created here inside each condition
#                examples: "0N_rep1", "0N_rep2", "5N_rep3"
#
# Edit here:
#   NULL = use all condition values present in pbmc_harmony$condition
#   n_pseudoreps = pseudo-replicates per condition
pseudobulk_conditions <- NULL
n_pseudoreps          <- 3

cell_type_subsets_replicates <- assign_pseudoreplicates_batch(cell_type_subsets,
                                                             pseudobulk_conditions = pseudobulk_conditions,
                                                             n_pseudoreps = n_pseudoreps)


# QC check — replace Pavement_Cell with any cell type name from your data:
table(cell_type_subsets_replicates$Pavement_Cell$condition)
table(cell_type_subsets_replicates$Pavement_Cell$replicate)
table(cell_type_subsets_replicates$Pavement_Cell$orig.ident)


# =============================================================================

message("\n✓ SECTION 15 COMPLETE: Pseudo-replicates assigned")
# SECTION 16 — PSEUDOBULK TABLES AND DESEQ2
# =============================================================================
# Aggregates counts by pseudo-replicate for each cell type, saves the resulting
# count tables, and runs DESeq2 for the user-defined pairwise contrasts.
#
# Edit here:
#   Use condition names, not orig.ident names and not replicate names.
#   Check them with: table(cell_type_subsets_replicates$Pavement_Cell$condition)
#
#   conds = c("reference_condition", "treatment_condition")
#   log2FC > 0 means higher expression in treatment_condition
#
#   Example:
#     conds = c("0N", "5N") means log2FC = log2(5N / 0N)
comparisons <- list(
  list(conds = c("condicion1", "condicion2"), tag = "condicion1_vs_condicion2")
)

# Edit here:
#   NULL = analyze all cell types
#   c("Guard Cell", "Mesophyll") = analyze only those cell types
cell_types_to_analyze <- NULL

output_dir <- dir_06

# Run pseudobulk aggregation and DESeq2 analysis
deseq2_results <- run_pseudobulk_deseq2_analysis(
  cell_type_subsets_replicates = cell_type_subsets_replicates,
  comparisons = comparisons,
  output_dir = output_dir,
  cell_types = cell_types_to_analyze,
  pseudobulk_dir = file.path(dir_objects, "pseudobulk_replicas")
)


# =============================================================================

message("\n✓ SECTION 16 COMPLETE: Pseudobulk aggregation and DESeq2 complete")
# SECTION 17 — VOLCANO PLOTS
# =============================================================================
# Renders one PNG volcano plot per cell type for a selected contrast and also
# combines them into a single PDF.
#
# ┌─ VOLCANO PARAMETERS ─────────────────────────────────────────────────────────
#   volcano_tag : tag of the contrast to visualize (must match comparisons)
#   padj_cut    : adjusted p-value threshold
#   lfc_cut     : absolute log2 fold-change threshold
# └─────────────────────────────────────────────────────────────────────────────
volcano_tag <- "condicion1_vs_condicion2"
padj_cut    <- 0.05
lfc_cut     <- 1

render_volcano_plots(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag, "volcano"),
  pdf_name    = paste0("VolcanoPlots_", volcano_tag, ".pdf"),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut
)


# =============================================================================

message("\n✓ SECTION 17 COMPLETE: Volcano plots saved")
# SECTION 18 — DIFFERENTIAL GENE TABLES
# =============================================================================
# Builds combined differential-expression summary tables for one selected
# contrast across all cell types.
#
# ┌─ DIFFERENTIAL TABLE PARAMETERS ──────────────────────────────────────────────
#   diff_prefix : output filename prefix for the discrete matrix
# └─────────────────────────────────────────────────────────────────────────────
diff_prefix <- paste0("diff_table_", volcano_tag)

diff_tables <- build_differential_tables(
  results_dir = file.path(dir_06, volcano_tag),
  output_dir  = file.path(dir_06, volcano_tag),
  padj_cut    = padj_cut,
  lfc_cut     = lfc_cut,
  prefix      = diff_prefix
)


# =============================================================================

message("\n✓ SECTION 18 COMPLETE: Differential gene tables saved")
# SECTION 19 — GO ENRICHMENT (SIMPLE)
# =============================================================================
# Gene Ontology enrichment per cell type for the selected contrast.

# Edit here:
#   go_space = "BP", "MF", or "CC"
#   Arabidopsis: go_orgdb = org.At.tair.db | go_keytype = "TAIR"
go_space    <- "BP"
go_orgdb    <- org.At.tair.db
go_keytype  <- "TAIR"
padj_cutoff <- 0.05

deseq2_files <- list.files(file.path(dir_06, volcano_tag),
                           pattern = "^DESeq2_.*\\.csv$",
                           full.names = TRUE)

for (deseq2_file in deseq2_files) {
  cell_type <- gsub("^DESeq2_|\\.csv$", "", basename(deseq2_file))

  deseq2_results <- read.csv(deseq2_file, row.names = 1)
  sig_genes <- rownames(deseq2_results)[deseq2_results$padj < padj_cutoff]

  if (length(sig_genes) > 0) {
    run_simple_go_enrichment(
      diff_table = data.frame(gene_id = sig_genes),
      output_dir = file.path(dir_07, volcano_tag),
      orgdb        = go_orgdb,
      keytype      = go_keytype,
      go_space = go_space,
      padj_cutoff = padj_cutoff,
      cell_type = cell_type,
      contrast_tag = volcano_tag
    )
  }
}

# =============================================================================

message("\n✓ SECTION 19 COMPLETE: GO enrichment complete")
# SECTION 20 — LOG2FC HEATMAP
# =============================================================================
# Heatmap of log2FC values across all cell types for the selected contrast.
# Genes are ordered by the internal hierarchical dendrogram (cluster_rows = TRUE).
#
# Edit here: color scale range for log2FC values.
heatmap_limits <- c(-5, 5)

build_logfc_heatmap(
  logfc_table  = diff_tables$logfc,
  contrast_tag = volcano_tag,
  output_dir   = file.path(dir_06, volcano_tag),
  limits       = heatmap_limits
)


# =============================================================================

message("\n✓ SECTION 20 COMPLETE: Log2FC heatmap saved")
# SECTION 21 - COEXPRESSION NETWORK (hdWGCNA) - UNIFICADO
# =============================================================================
# Filtra la matriz a los DEGs de la tabla resumen y corre hdWGCNA UNA SOLA VEZ
# sobre todas las celulas. Metacells se construyen por celltype x sample para
# preservar la estructura biologica, pero WGCNA actua sobre el pool completo
# de genes diferenciales generando un unico set de modulos.
#
# Edit here:
#   n_metacells = metacells per celltype x sample
#   soft_power  = NULL for automatic detection, or use a number
wgcna_name  <- "unified"
n_metacells <- 25
soft_power  <- NULL

# -- 1. Leer DEGs desde tabla resumen -----------------------------------------
de_table_path <- file.path(dir_06, volcano_tag, "tabla_log2FC_fc1_padj_005.tsv")
de_table <- read.table(de_table_path, header = TRUE, sep = "\t",
                       row.names = 1, check.names = FALSE)
de_genes <- rownames(de_table)[apply(!is.na(de_table), 1, any)]
de_genes <- intersect(de_genes, rownames(pbmc_harmony))
cat(sprintf("  DEGs para hdWGCNA: %d / %d genes totales\n",
            length(de_genes), nrow(pbmc_harmony)))

# -- 2. Filtrar objeto a DEGs -------------------------------------------------
pbmc_de <- pbmc_harmony[de_genes, ]
pbmc_de$all_group <- "all"

# -- 3. Setup hdWGCNA ---------------------------------------------------------
message("  Configurando hdWGCNA unificado...")
obj <- hdWGCNA::SetupForWGCNA(pbmc_de, gene_select = "all", wgcna_name = wgcna_name)

# Metacells por celltype x sample — preserva estructura biologica
# ident.group = "all_group" para usar todos los metacells juntos en SetDatExpr
obj <- hdWGCNA::MetacellsByGroups(
  seurat_obj  = obj,
  group.by    = c(pseudobulk_annot_col, "orig.ident", "all_group"),
  reduction   = "harmony",
  k           = n_metacells,
  max_shared  = 10,
  ident.group = "all_group",
  wgcna_name  = wgcna_name
)
obj <- hdWGCNA::NormalizeMetacells(obj, wgcna_name = wgcna_name)

# SetDatExpr sobre TODOS los metacells juntos
obj <- hdWGCNA::SetDatExpr(obj, group_name = "all", group.by = "all_group",
                            assay = "RNA", layer = "data", wgcna_name = wgcna_name)

# -- 4. Soft power ------------------------------------------------------------
message("  Detectando soft power...")
obj <- hdWGCNA::TestSoftPowers(obj, networkType = "signed hybrid", wgcna_name = wgcna_name)
sp <- if (!is.null(soft_power)) soft_power else {
  pwr_tbl <- hdWGCNA::GetPowerTable(obj, wgcna_name = wgcna_name)
  best    <- pwr_tbl$Power[which(pwr_tbl$SFT.R.sq >= 0.8)[1]]
  if (is.na(best)) 6L else as.integer(best)
}
cat("  Soft power:", sp, "\n")

# -- 5. Construir red y detectar modulos --------------------------------------
message("  Construyendo red TOM...")
obj <- hdWGCNA::ConstructNetwork(
  obj,
  soft_power    = sp,
  networkType   = "signed hybrid",
  tom_outdir    = sub("^/workspace/", "", dir_08),
  maxBlockSize  = max(length(de_genes) + 1L, 30000L),
  useDiskCache  = FALSE,
  overwrite_tom = TRUE,
  wgcna_name    = wgcna_name
)
obj <- hdWGCNA::ModuleEigengenes(obj, wgcna_name = wgcna_name)
obj <- hdWGCNA::ModuleConnectivity(obj, group.by = "all_group",
                                    group_name = "all", wgcna_name = wgcna_name)

modules   <- hdWGCNA::GetModules(obj, wgcna_name = wgcna_name)
hub_genes <- hdWGCNA::GetHubGenes(obj, n_hubs = 20, wgcna_name = wgcna_name)

# -- 6. Guardar ---------------------------------------------------------------
write.table(modules,   file.path(dir_08, "modules_unified.tsv"),  sep="\t", quote=FALSE, row.names=FALSE)
write.table(hub_genes, file.path(dir_08, "hubgenes_unified.tsv"), sep="\t", quote=FALSE, row.names=FALSE)
saveRDS(obj, file.path(dir_08, "hdwgcna_unified.rds"))
n_mods <- length(unique(modules$module[modules$module != "grey"]))
cat(sprintf("  Modulos detectados: %d\n", n_mods))

# -- 7. Plots: UMAP modulos, heatmap eigengenes, dendrograma ------------------
plot_list <- hdWGCNA::ModuleFeaturePlot(obj, features="hMEs", order=TRUE, wgcna_name=wgcna_name)
plot_list <- plot_list[!grepl("grey", names(plot_list), ignore.case=TRUE)]
plot_list <- lapply(plot_list, function(p) p + ggplot2::theme(
  axis.text=ggplot2::element_blank(), axis.ticks=ggplot2::element_blank()))
pdf(file.path(dir_08, "umap_modules_unified.pdf"), width=16, height=12)
print(patchwork::wrap_plots(plot_list, ncol=4) +
      patchwork::plot_annotation(
        title    = "UMAP Modulos WGCNA unificado",
        subtitle = sprintf("%d DEGs | %d modulos", length(de_genes), n_mods)))
dev.off()

MEs <- hdWGCNA::GetMEs(obj, harmonized=FALSE, wgcna_name=wgcna_name)
if (!is.null(MEs) && ncol(MEs) > 0) {
  me_cols <- colnames(MEs)[!grepl("grey|^0$", colnames(MEs), ignore.case=TRUE)]
  if (length(me_cols) > 0) {
    me_mat  <- t(as.matrix(MEs[, me_cols, drop=FALSE]))
    mod_col <- sub("^(ME|hME)", "", rownames(me_mat))
    pdf(file.path(dir_08, "eigengene_heatmap_unified.pdf"),
        width=12, height=max(4, nrow(me_mat)*0.5+2))
    ComplexHeatmap::draw(ComplexHeatmap::Heatmap(me_mat, name="ME",
      col=viridis::viridis(100), cluster_rows=TRUE, cluster_columns=TRUE,
      show_row_names=TRUE, row_labels=mod_col, show_column_names=FALSE,
      column_title=sprintf("Module eigengenes unificado (%d DEGs)", length(de_genes))))
    dev.off()
  }
}
pdf(file.path(dir_08, "dendrogram_unified.pdf"), width=14, height=6)
hdWGCNA::PlotDendrogram(obj,
  main=sprintf("Dendrograma unificado | %d DEGs | %d modulos", length(de_genes), n_mods),
  wgcna_name=wgcna_name)
dev.off()

message("\n\u2713 SECTION 21 COMPLETE: hdWGCNA co-expression networks saved")


# =============================================================================
# SECTION 22 — NETWORK EXPORT & VISUALIZATION
# =============================================================================
# Reads the hdWGCNA objects saved by Section 21 and for each cell type:
#   • Exports edges (source, target, weight) and nodes (gene, module, kME)
#   • Plots a co-expression network PDF coloured by module, sized by kME
#
# Edit here:
#   tom_threshold = lower gives more edges; higher gives simpler networks
#   cell_types_network = NULL for all
#   n_hub_label = number of hub genes labelled in the plot
tom_threshold      <- 0.1
cell_types_network <- NULL
n_hub_label        <- 5

plot_hdwgcna_network(
  hdwgcna_dir   = dir_08,
  output_dir    = dir_08,
  tom_threshold = tom_threshold,
  cell_types    = cell_types_network,
  n_hub_label   = n_hub_label
)

message("\n✓ SECTION 22 COMPLETE: Network files and plots saved")


# =============================================================================
# SECTION 23 — OMITTED
# =============================================================================
# The network in Sections 21-22 is unified, not one network per cell type.
# The old DE-filtered network helper expects cell-type-specific hdWGCNA RDS
# files, so it does not apply to this unified-network design.
#
# Capitulo 2 ends at Section 22:
#   DESeq2 + volcano + GO + log2FC heatmap + unified hdWGCNA network.
